from .mobilenetv3q import mobilenet_v3_large as mobilenet_v3_large
from .resnetq import resnet18 as resnet_18
from .resnetq import resnet50 as resnet_50
from .resnetq import resnext101_32x8d as resnext_101
from .googlenetq import googlenet as googlenet
from .shufflenetv2q import shufflenet_v2_x1_0 as shufflenet_v2
from .inceptionq import inception_v3 as inception_v3
from .mobilenetv2q import mobilenet_v2 as mobilenet_v2
from .ghostnet import ghostnet as ghostnet